
name: ia-swift-ci
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "*" ] 

jobs:
  cleanTest:  
    runs-on: macos-latest
    env:
        PROJECT: App/App.xcodeproj
        SCHEME: Default
        DESTINATION: platform=iOS Simulator,name=iPod touch (7th generation),OS=latest
        CONFIGURATION: Debug
    steps:
    - uses: actions/checkout@v3  
    
    - name : Select XCode Version
      run : sudo xcode-select -switch /Applications/Xcode.app
    
    - name : Install xcpretty
      run : sudo gem install xcpretty

    - name: Xcodebuild Clean Test
      run: xcodebuild clean test
           -project "$PROJECT"
           -scheme "$SCHEME"
           -configuration "$CONFIGURATION"
           -destination "$DESTINATION"
           -enableCodeCoverage YES | xcpretty --color
           -showBuildTimingSummary
           
    - name: IA iOS CI Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: ✅ Idea Archive iOS CI success ✅
        webhook: ${{ secrets.IOS_DISCORD_WEBHOOK }}
        color: 00FF00

    - name: IA iOS CI Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: ❗️ Idea Archive iOS CI failed ❗️
        webhook: ${{ secrets.IOS_DISCORD_WEBHOOK }}
        color: FF0000
