
name: ia-swift-ci
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "*" ] 

jobs:
  cleanTest:  
    runs-on: macos-latest
    env:
        PROJECT: App/App.xcodeproj
        SCHEME: Default
        DESTINATION: platform=iOS Simulator,name=iPod touch (7th generation),OS=latest
        CONFIGURATION: Debug
    steps:
    - uses: actions/checkout@v3  
    
    - name : Select XCode Version
      run : sudo xcode-select -switch /Applications/Xcode.app
    
    - name : Install xcpretty
      run : sudo gem install xcpretty

    - name: Xcodebuild Clean Test
      run: xcodebuild clean test
           -project "$PROJECT"
           -scheme "$SCHEME"
           -configuration "$CONFIGURATION"
           -destination "$DESTINATION"
           -enableCodeCoverage YES | xcpretty --color
           -showBuildTimingSummary
